import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useSession, signIn, signOut } from "next-auth/react";
import Dashboard from './dashboard';
import Header from '@/components/Header/Header';
import SideMenu from '@/components/SideMenu/SideMenu';
import Login from './login';
import scss from './Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

const Home: React.FC = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>DataSoft - Data Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={scss.main}>
        {
          session && (
            <>
              <SideMenu />
              <Dashboard />
            </>
          )
        }
        <Login/>
      </main>
    </>
  )
}

export default Home;